//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace AccessConsole.DataModels
{
	/// <summary>
	/// Database       : ProjectData
	/// Data Source    : C:\Users\Sean_L1\Desktop\AccessConsole\AccessConsole\DataModels../../App_Data/\ProjectData.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class ProjectDataDB : LinqToDB.Data.DataConnection
	{
		public ITable<CONTAINERTABLE>   CONTAINERTABLE    { get { return this.GetTable<CONTAINERTABLE>(); } }
		public ITable<FUNCTIONSETTING>  FUNCTIONSETTING   { get { return this.GetTable<FUNCTIONSETTING>(); } }
		public ITable<ICINFO>           ICINFO            { get { return this.GetTable<ICINFO>(); } }
		public ITable<LOTSETTING>       LOTSETTING        { get { return this.GetTable<LOTSETTING>(); } }
		public ITable<MSysCompactError> MSysCompactErrors { get { return this.GetTable<MSysCompactError>(); } }
		public ITable<OPTICALSETTING>   OPTICALSETTING    { get { return this.GetTable<OPTICALSETTING>(); } }
		public ITable<SOCKETPICKPLACE>  SOCKETPICKPLACE   { get { return this.GetTable<SOCKETPICKPLACE>(); } }
		public ITable<SOCKETSETTING>    SOCKETSETTING     { get { return this.GetTable<SOCKETSETTING>(); } }
		public ITable<Test>             Tests             { get { return this.GetTable<Test>(); } }

		public ProjectDataDB()
		{
			InitDataContext();
		}

		public ProjectDataDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("CONTAINER_TABLE")]
	public partial class CONTAINERTABLE
	{
		[Column("CONTAINER_NAME"),     Nullable] public string CONTAINERNAME     { get; set; } // text(255)
		[Column("CONTAINER_TYPE"),     Nullable] public string CONTAINERTYPE     { get; set; } // text(255)
		[Column("POS_CODE"),           Nullable] public string POSCODE           { get; set; } // text(255)
		[Column("CARRIER_NAME"),       Nullable] public string CARRIERNAME       { get; set; } // text(255)
		[Column(),                     Nullable] public string ANGLE             { get; set; } // text(255)
		[Column(),                     Nullable] public string MATRIX            { get; set; } // text(255)
		[Column("SPACE_PITCH"),        Nullable] public string SPACEPITCH        { get; set; } // text(255)
		[Column("SPACE_SIZE"),         Nullable] public string SPACESIZE         { get; set; } // text(255)
		[Column("LAST_COORDINATE"),    Nullable] public string LASTCOORDINATE    { get; set; } // text(255)
		[Column("FIRST_COORDINATE"),   Nullable] public string FIRSTCOORDINATE   { get; set; } // text(255)
		[Column("START_ENABLEDINDEX"), Nullable] public string STARTENABLEDINDEX { get; set; } // text(255)
		[Column("END_ENABLEDINDEX"),   Nullable] public string ENDENABLEDINDEX   { get; set; } // text(255)
		[Column("IGNORE_PICKERROR"),   Nullable] public string IGNOREPICKERROR   { get; set; } // text(255)
		[Column("PICKERROR_METHOD"),   Nullable] public string PICKERRORMETHOD   { get; set; } // text(255)
		[Column("PICK_DEPTH"),         Nullable] public string PICKDEPTH         { get; set; } // text(255)
		[Column("PLACE_DEPTH"),        Nullable] public string PLACEDEPTH        { get; set; } // text(255)
	}

	[Table("FUNCTION_SETTING")]
	public partial class FUNCTIONSETTING
	{
		[Column("FUNCTION_NAME"),     Nullable] public string FUNCTIONNAME     { get; set; } // text(255)
		[Column("SERIALSTOP_ENABLE"), Nullable] public string SERIALSTOPENABLE { get; set; } // text(255)
		[Column("SERIALSTOP_LIMIT"),  Nullable] public string SERIALSTOPLIMIT  { get; set; } // text(255)
		[Column("FUNCTION_ENABLE"),   Nullable] public string FUNCTIONENABLE   { get; set; } // text(255)
	}

	[Table("IC_INFO")]
	public partial class ICINFO
	{
		[Column("ICINFO_KEY"),   PrimaryKey,  NotNull] public string ICINFOKEY   { get; set; } // text(255)
		[Column("ICINFO_VALUE"),    Nullable         ] public string ICINFOVALUE { get; set; } // text(255)
	}

	[Table("LOT_SETTING")]
	public partial class LOTSETTING
	{
		[Column("LOTSETTING_KEY"),    Nullable] public string LOTSETTINGKEY    { get; set; } // text(255)
		[Column("LOTSETTIONG_VALUE"), Nullable] public string LOTSETTIONGVALUE { get; set; } // text(255)
	}

	[Table("MSysCompactError")]
	public partial class MSysCompactError
	{
		[Column, Nullable] public int?   ErrorCode        { get; set; } // Long
		[Column, Nullable] public string ErrorDescription { get; set; } // text(0)
		[Column, Nullable] public byte[] ErrorRecid       { get; set; } // image(510)
		[Column, Nullable] public string ErrorTable       { get; set; } // text(255)
	}

	[Table("OPTICAL_SETTING")]
	public partial class OPTICALSETTING
	{
		[Column("FUNCTION_CODE"),    Nullable] public string FUNCTIONCODE    { get; set; } // text(255)
		[Column(),                   Nullable] public string TOLERANCEX      { get; set; } // text(255)
		[Column(),                   Nullable] public string TOLERANCEY      { get; set; } // text(255)
		[Column(),                   Nullable] public string TOLERANCEU      { get; set; } // text(255)
		[Column("TOLERANCE_TIMES"),  Nullable] public string TOLERANCETIMES  { get; set; } // text(255)
		[Column("LIGHT_BRIGHTNESS"), Nullable] public string LIGHTBRIGHTNESS { get; set; } // text(255)
	}

	[Table("SOCKET_PICKPLACE")]
	public partial class SOCKETPICKPLACE
	{
		[Column("MODULE_INDEX"),      Nullable] public string MODULEINDEX      { get; set; } // text(255)
		[Column("SOCKET_INDEX"),      Nullable] public string SOCKETINDEX      { get; set; } // text(255)
		[Column("SOCKET_COORDINATE"), Nullable] public string SOCKETCOORDINATE { get; set; } // text(255)
		[Column("SOCKET_PICKDEPTH"),  Nullable] public string SOCKETPICKDEPTH  { get; set; } // text(255)
		[Column("SOCKET_PLACEDEPTH"), Nullable] public string SOCKETPLACEDEPTH { get; set; } // text(255)
	}

	[Table("SOCKET_SETTING")]
	public partial class SOCKETSETTING
	{
		[Column("MODULE_NAME"),      Nullable] public string MODULENAME      { get; set; } // text(255)
		[Column("SOCKET_INDEX"),     Nullable] public string SOCKETINDEX     { get; set; } // text(255)
		[Column("SOCKET_USEDCOUNT"), Nullable] public string SOCKETUSEDCOUNT { get; set; } // text(255)
		[Column("SOCKET_USEDLIMIT"), Nullable] public string SOCKETUSEDLIMIT { get; set; } // text(255)
		[Column("SOCKET_NGLIMIT"),   Nullable] public string SOCKETNGLIMIT   { get; set; } // text(255)
		[Column("SOCKET_NGCOUNT"),   Nullable] public string SOCKETNGCOUNT   { get; set; } // text(255)
		[Column("NGSTOP_ENABLE"),    Nullable] public string NGSTOPENABLE    { get; set; } // text(255)
	}

	[Table("Test")]
	public partial class Test
	{
		[PrimaryKey, Nullable] public Guid?  Id        { get; set; } // GUID
		[Column,     Nullable] public short? Age       { get; set; } // Short
		[Column,     Nullable] public string FirstName { get; set; } // text(255)
	}

	public static partial class TableExtensions
	{
		public static ICINFO Find(this ITable<ICINFO> table, string ICINFOKEY)
		{
			return table.FirstOrDefault(t =>
				t.ICINFOKEY == ICINFOKEY);
		}

		public static Test Find(this ITable<Test> table, Guid? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
